version: '2'
services:
  kong-dashboard:
    image: pgbi/kong-dashboard:v3.3.0
    restart: on-failure
    command:
    - start --kong-url http://kong:8001 --basic-auth admin=admin
    ports:
    - 8081:8080

  kong-db:
    image: postgres:9.6
    environment:
      POSTGRES_DB: kong
      POSTGRES_USER: kong
      POSTGRES_PASSWORD: SHUNTeRTosTOneDw

  kong:
    image: kong:0.13.1
    restart: always
    command: 'kong start --run-migrations'
    depends_on:
    - kong-db
    ports:
    - 8000:8000
    - 8443:8443
    - 8001:8001
    - 7946:7946
    - 7946:7946/udp
    environment:
    - KONG_DATABASE=postgres
    - KONG_PG_HOST=kong-db
    - KONG_PG_PASSWORD=SHUNTeRTosTOneDw
    - KONG_ADMIN_LISTEN=0.0.0.0:8001